# Uncomment this file to enable multilanguage site support

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "slhmy 的博客"
contentDir = "content/zh-cn"

[en]
languageName = "English"
languagedirection = "ltr"
title = "slhmy's blog"
contentDir = "content/en"